# Generated by Django 2.2.2 on 2019-07-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
