# Generated by Django 2.2.2 on 2019-07-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(max_length=30)),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
    ]
