# Generated by Django 2.2.2 on 2019-07-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
